import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const BASE_INSTRUCTION = "Using this face as reference for the character's appearance, generate a full upper-body portrait (head, shoulders, and upper torso visible) of this same person/character. Keep the exact same face, hair, and style. The character should be wearing a casual outfit.";

const EMOTION_PROMPTS: Record<string, string> = {
  happy: `${BASE_INSTRUCTION} Show a happy, joyful expression with a bright smile and cheerful eyes.`,
  smirk: `${BASE_INSTRUCTION} Show a smug, mischievous smirk with one eyebrow slightly raised.`,
  excited: `${BASE_INSTRUCTION} Show an excited, energetic expression with wide sparkling eyes and an open enthusiastic smile.`,
  angry: `${BASE_INSTRUCTION} Show an angry, frustrated expression with furrowed brows, narrowed eyes, and a frown.`,
  shy: `${BASE_INSTRUCTION} Show a shy, bashful expression with a slight blush, averted gaze, and a small nervous smile.`,
  sad: `${BASE_INSTRUCTION} Show a sad, melancholic expression with downturned mouth and droopy eyes.`,
  love: `${BASE_INSTRUCTION} Show a loving, adoring expression with sparkling eyes, a warm dreamy smile, and a deep blush.`,
  proud: `${BASE_INSTRUCTION} Show a proud, confident expression with chin slightly raised and a satisfied grin.`,
  thinking: `${BASE_INSTRUCTION} Show a thoughtful, contemplative expression with one hand near the chin and eyes looking upward.`,
  confused: `${BASE_INSTRUCTION} Show a confused, puzzled expression with a tilted head and raised eyebrow.`,
  sleepy: `${BASE_INSTRUCTION} Show a sleepy, drowsy expression with half-closed droopy eyes and a yawn.`,
  jealous: `${BASE_INSTRUCTION} Show a jealous, envious expression with narrowed suspicious eyes and a slight pout.`,
  embarrassed: `${BASE_INSTRUCTION} Show an embarrassed, flustered expression with a deep blush and wide surprised eyes.`,
  shock: `${BASE_INSTRUCTION} Show a shocked, surprised expression with wide open eyes and an open mouth.`,
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { baseImage, emotion, userId } = await req.json();
    if (!baseImage || !emotion || !userId) {
      throw new Error("Missing baseImage, emotion, or userId");
    }

    const prompt = EMOTION_PROMPTS[emotion];
    if (!prompt) throw new Error(`Unknown emotion: ${emotion}`);

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    console.log(`Generating ${emotion} expression for user ${userId}`);

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              { type: "image_url", image_url: { url: baseImage } },
            ],
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limited, please wait and try again" }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "Credits needed" }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const data = await response.json();
    const generatedImage = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!generatedImage) {
      throw new Error("No image generated by AI");
    }

    // Upload to storage
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Convert base64 to Uint8Array
    const base64Data = generatedImage.replace(/^data:image\/\w+;base64,/, "");
    const binaryString = atob(base64Data);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }

    const path = `${userId}/${emotion}.png`;
    const { error: uploadError } = await supabase.storage
      .from("character-avatars")
      .upload(path, bytes, { contentType: "image/png", upsert: true });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      throw new Error(`Storage upload failed: ${uploadError.message}`);
    }

    const { data: urlData } = supabase.storage
      .from("character-avatars")
      .getPublicUrl(path);

    const publicUrl = urlData.publicUrl + `?t=${Date.now()}`;

    return new Response(
      JSON.stringify({ success: true, emotion, imageUrl: publicUrl }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("aori-generate-expressions error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
